FROM continuumio/miniconda3

SHELL ["/bin/bash", "-c"]

WORKDIR ${HOME}

ENV DEBIAN_FRONTEND=noninteractive

# Basic setup
RUN apt-get update && apt-get install -y --no-install-recommends --allow-unauthenticated \
    autoconf \
    automake \
    bash-completion \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    g++ \
    git \
    iproute2 \
    iputils-ping \
    libxext-dev \
    libx11-dev \
    make \
    mc \
    mesa-utils \
    nano \
    vim \
    tree \
    pkg-config \
    sudo \
    tmux \
    tzdata \
    xclip \
    python3-tk \
    x11proto-gl-dev && \
    rm -rf /var/lib/apt/lists/*

# install VS Code server
RUN curl -fsSL https://code-server.dev/install.sh | sh

# install python extension
RUN code-server --install-extension ms-python.python

# Set datetime and timezone correctly
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo '$TZ' | sudo tee -a /etc/timezone

ENV DEBIAN_FRONTEND=dialog

# Setup conda env

# defaults
ARG userid=1002
ARG groupid=1002

RUN groupadd -g ${groupid} -o robot
RUN useradd -ms /bin/bash --uid ${userid} -g ${groupid} robot
USER robot
WORKDIR /home/robot

# Copy with ownership
COPY --chown=robot:robot config/environment.yml /tmp/environment.yml

RUN conda env create -f /tmp/environment.yml
RUN echo "source activate lab-2" >> ~/.bashrc
ENV PATH /opt/conda/envs/lab-2/bin:$PATH

RUN mkdir -p lab-2/src

# Setup tmux config
ADD --chown=robot:robot https://raw.githubusercontent.com/MarylandRoboticsCenter/someConfigs/refs/heads/master/.tmux_K.conf /home/robot/.tmux.conf

ENTRYPOINT ["/bin/bash", "-i"]